networks:
  diario-bordo-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  nginx-cache:
    driver: local
  portainer-data:
    driver: local

services:
  # Base de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: diario-bordo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: DiarioBordo2024!
      MYSQL_DATABASE: diario_bordo
      MYSQL_USER: diario_user
      MYSQL_PASSWORD: DiarioUser2024!
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      - diario-bordo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    command: --default-authentication-plugin=mysql_native_password --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO

  # Cache Redis
  redis:
    image: redis:7-alpine
    container_name: diario-bordo-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - diario-bordo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: redis-server /usr/local/etc/redis/redis.conf

  # Backend API .NET
  api:
    build:
      context: .
      dockerfile: src/DiarioBordo.API/Dockerfile
    container_name: diario-bordo-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=diario_bordo;User=diario_user;Password=DiarioUser2024!;Port=3306;SslMode=None;AllowPublicKeyRetrieval=true;
      - ConnectionStrings__Redis=redis:6379
      - JWT__SecretKey=DiarioBordoSecretKey2024VeryLongAndSecureKey123!
      - JWT__Issuer=DiarioBordo
      - JWT__Audience=DiarioBordoApp
      - JWT__ExpirationMinutes=15
      - JWT__RefreshExpirationDays=7
      - ANAC__SyncEnabled=true
      - ANAC__SyncIntervalHours=1
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    ports:
      - "8191:8080"
    networks:
      - diario-bordo-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: diario-bordo-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - diario-bordo-network
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Proxy Reverso Nginx
  nginx:
    image: nginx:alpine
    container_name: diario-bordo-nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - diario-bordo-network
    depends_on:
      - frontend
      - api
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Monitoramento com Portainer (opcional)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: diario-bordo-portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - "9000:9000"
    networks:
      - diario-bordo-network
